package dev.hypix.reactor.api.world.block;

import lombok.Getter;

/* Autogenerated - Don't touch :) */
@Getter
public final class Banner {

    public static final Banner[] ALL = new Banner[43];

    private final String id, translation;

    public Banner(final String id, final String translation) {
        this.id = id;
        this.translation = translation;
    }

    private Banner(final String id, final String translation, final int index) {
        this.id = id;
        this.translation = translation;
        ALL[index] = this;
    }

    public static final Banner
        BASE = new Banner("minecraft:base","block.minecraft.banner.base",0),
        BORDER = new Banner("minecraft:border","block.minecraft.banner.border",1),
        BRICKS = new Banner("minecraft:bricks","block.minecraft.banner.bricks",2),
        CIRCLE = new Banner("minecraft:circle","block.minecraft.banner.circle",3),
        CREEPER = new Banner("minecraft:creeper","block.minecraft.banner.creeper",4),
        CROSS = new Banner("minecraft:cross","block.minecraft.banner.cross",5),
        CURLY_BORDER = new Banner("minecraft:curly_border","block.minecraft.banner.curly_border",6),
        DIAGONAL_LEFT = new Banner("minecraft:diagonal_left","block.minecraft.banner.diagonal_left",7),
        DIAGONAL_RIGHT = new Banner("minecraft:diagonal_right","block.minecraft.banner.diagonal_right",8),
        DIAGONAL_UP_LEFT = new Banner("minecraft:diagonal_up_left","block.minecraft.banner.diagonal_up_left",9),
        DIAGONAL_UP_RIGHT = new Banner("minecraft:diagonal_up_right","block.minecraft.banner.diagonal_up_right",10),
        FLOW = new Banner("minecraft:flow","block.minecraft.banner.flow",11),
        FLOWER = new Banner("minecraft:flower","block.minecraft.banner.flower",12),
        GLOBE = new Banner("minecraft:globe","block.minecraft.banner.globe",13),
        GRADIENT = new Banner("minecraft:gradient","block.minecraft.banner.gradient",14),
        GRADIENT_UP = new Banner("minecraft:gradient_up","block.minecraft.banner.gradient_up",15),
        GUSTER = new Banner("minecraft:guster","block.minecraft.banner.guster",16),
        HALF_HORIZONTAL = new Banner("minecraft:half_horizontal","block.minecraft.banner.half_horizontal",17),
        HALF_HORIZONTAL_BOTTOM = new Banner("minecraft:half_horizontal_bottom","block.minecraft.banner.half_horizontal_bottom",18),
        HALF_VERTICAL = new Banner("minecraft:half_vertical","block.minecraft.banner.half_vertical",19),
        HALF_VERTICAL_RIGHT = new Banner("minecraft:half_vertical_right","block.minecraft.banner.half_vertical_right",20),
        MOJANG = new Banner("minecraft:mojang","block.minecraft.banner.mojang",21),
        PIGLIN = new Banner("minecraft:piglin","block.minecraft.banner.piglin",22),
        RHOMBUS = new Banner("minecraft:rhombus","block.minecraft.banner.rhombus",23),
        SKULL = new Banner("minecraft:skull","block.minecraft.banner.skull",24),
        SMALL_STRIPES = new Banner("minecraft:small_stripes","block.minecraft.banner.small_stripes",25),
        SQUARE_BOTTOM_LEFT = new Banner("minecraft:square_bottom_left","block.minecraft.banner.square_bottom_left",26),
        SQUARE_BOTTOM_RIGHT = new Banner("minecraft:square_bottom_right","block.minecraft.banner.square_bottom_right",27),
        SQUARE_TOP_LEFT = new Banner("minecraft:square_top_left","block.minecraft.banner.square_top_left",28),
        SQUARE_TOP_RIGHT = new Banner("minecraft:square_top_right","block.minecraft.banner.square_top_right",29),
        STRAIGHT_CROSS = new Banner("minecraft:straight_cross","block.minecraft.banner.straight_cross",30),
        STRIPE_BOTTOM = new Banner("minecraft:stripe_bottom","block.minecraft.banner.stripe_bottom",31),
        STRIPE_CENTER = new Banner("minecraft:stripe_center","block.minecraft.banner.stripe_center",32),
        STRIPE_DOWNLEFT = new Banner("minecraft:stripe_downleft","block.minecraft.banner.stripe_downleft",33),
        STRIPE_DOWNRIGHT = new Banner("minecraft:stripe_downright","block.minecraft.banner.stripe_downright",34),
        STRIPE_LEFT = new Banner("minecraft:stripe_left","block.minecraft.banner.stripe_left",35),
        STRIPE_MIDDLE = new Banner("minecraft:stripe_middle","block.minecraft.banner.stripe_middle",36),
        STRIPE_RIGHT = new Banner("minecraft:stripe_right","block.minecraft.banner.stripe_right",37),
        STRIPE_TOP = new Banner("minecraft:stripe_top","block.minecraft.banner.stripe_top",38),
        TRIANGLE_BOTTOM = new Banner("minecraft:triangle_bottom","block.minecraft.banner.triangle_bottom",39),
        TRIANGLE_TOP = new Banner("minecraft:triangle_top","block.minecraft.banner.triangle_top",40),
        TRIANGLES_BOTTOM = new Banner("minecraft:triangles_bottom","block.minecraft.banner.triangles_bottom",41),
        TRIANGLES_TOP = new Banner("minecraft:triangles_top","block.minecraft.banner.triangles_top",42);
}
