/*
* Autogenerated file. Please don't touch :)
* Class generator: dev.hypix.dataparser.registry.painting.PaintingParser (module data-parser)
* Date: Year: 2025. Month: 01. Day: 14. Time: 17:34:14
*/
package dev.hypix.reactor.api.world.block;
import lombok.Getter;

import java.util.Collection;

import dev.hypix.reactor.api.util.collection.CopyOnWriteCollection;

@Getter
public final class Painting {

    public static final Collection<Painting> ALL = new CopyOnWriteCollection<>(50);

    private final String assetId, title, author;
    private final byte height, width;

    public Painting(String assetId, byte height, byte width, String title, String author) {
        this.assetId = assetId;
        this.height = height;
        this.width = width;
        this.title = title;
        this.author = author;
    }

    private Painting(String assetId, int index, int height, int width, String title, String author) {
        this(assetId, (byte)height, (byte)width, title, author);
        ALL.add(this);
    }

    public static final Painting 
        PASSAGE = new Painting("minecraft:passage",0,2,4,"painting.minecraft.passage.title","painting.minecraft.passage.author"),
        PIGSCENE = new Painting("minecraft:pigscene",1,4,4,"painting.minecraft.pigscene.title","painting.minecraft.pigscene.author"),
        BURNING_SKULL = new Painting("minecraft:burning_skull",2,4,4,"painting.minecraft.burning_skull.title","painting.minecraft.burning_skull.author"),
        MEDITATIVE = new Painting("minecraft:meditative",3,1,1,"painting.minecraft.meditative.title","painting.minecraft.meditative.author"),
        CHANGING = new Painting("minecraft:changing",4,2,4,"painting.minecraft.changing.title","painting.minecraft.changing.author"),
        BOMB = new Painting("minecraft:bomb",5,1,1,"painting.minecraft.bomb.title","painting.minecraft.bomb.author"),
        ALBAN = new Painting("minecraft:alban",6,1,1,"painting.minecraft.alban.title","painting.minecraft.alban.author"),
        FIGHTERS = new Painting("minecraft:fighters",7,2,4,"painting.minecraft.fighters.title","painting.minecraft.fighters.author"),
        SKELETON = new Painting("minecraft:skeleton",8,3,4,"painting.minecraft.skeleton.title","painting.minecraft.skeleton.author"),
        COTAN = new Painting("minecraft:cotan",9,3,3,"painting.minecraft.cotan.title","painting.minecraft.cotan.author"),
        FERN = new Painting("minecraft:fern",10,3,3,"painting.minecraft.fern.title","painting.minecraft.fern.author"),
        FIRE = new Painting("minecraft:fire",11,2,2,"painting.minecraft.fire.title",null),
        LOWMIST = new Painting("minecraft:lowmist",12,2,4,"painting.minecraft.lowmist.title","painting.minecraft.lowmist.author"),
        POINTER = new Painting("minecraft:pointer",13,4,4,"painting.minecraft.pointer.title","painting.minecraft.pointer.author"),
        VOID = new Painting("minecraft:void",14,2,2,"painting.minecraft.void.title","painting.minecraft.void.author"),
        BAROQUE = new Painting("minecraft:baroque",15,2,2,"painting.minecraft.baroque.title","painting.minecraft.baroque.author"),
        POOL = new Painting("minecraft:pool",16,1,2,"painting.minecraft.pool.title","painting.minecraft.pool.author"),
        AZTEC = new Painting("minecraft:aztec",17,1,1,"painting.minecraft.aztec.title","painting.minecraft.aztec.author"),
        BOUQUET = new Painting("minecraft:bouquet",18,3,3,"painting.minecraft.bouquet.title","painting.minecraft.bouquet.author"),
        UNPACKED = new Painting("minecraft:unpacked",19,4,4,"painting.minecraft.unpacked.title","painting.minecraft.unpacked.author"),
        CAVEBIRD = new Painting("minecraft:cavebird",20,3,3,"painting.minecraft.cavebird.title","painting.minecraft.cavebird.author"),
        FINDING = new Painting("minecraft:finding",21,2,4,"painting.minecraft.finding.title","painting.minecraft.finding.author"),
        WATER = new Painting("minecraft:water",22,2,2,"painting.minecraft.water.title",null),
        DONKEY_KONG = new Painting("minecraft:donkey_kong",23,3,4,"painting.minecraft.donkey_kong.title","painting.minecraft.donkey_kong.author"),
        CREEBET = new Painting("minecraft:creebet",24,1,2,"painting.minecraft.creebet.title","painting.minecraft.creebet.author"),
        SKULL_AND_ROSES = new Painting("minecraft:skull_and_roses",25,2,2,"painting.minecraft.skull_and_roses.title","painting.minecraft.skull_and_roses.author"),
        PLANT = new Painting("minecraft:plant",26,1,1,"painting.minecraft.plant.title","painting.minecraft.plant.author"),
        WIND = new Painting("minecraft:wind",27,2,2,"painting.minecraft.wind.title",null),
        PRAIRIE_RIDE = new Painting("minecraft:prairie_ride",28,2,1,"painting.minecraft.prairie_ride.title","painting.minecraft.prairie_ride.author"),
        HUMBLE = new Painting("minecraft:humble",29,2,2,"painting.minecraft.humble.title","painting.minecraft.humble.author"),
        POND = new Painting("minecraft:pond",30,4,3,"painting.minecraft.pond.title","painting.minecraft.pond.author"),
        WASTELAND = new Painting("minecraft:wasteland",31,1,1,"painting.minecraft.wasteland.title","painting.minecraft.wasteland.author"),
        GRAHAM = new Painting("minecraft:graham",32,2,1,"painting.minecraft.graham.title","painting.minecraft.graham.author"),
        SUNFLOWERS = new Painting("minecraft:sunflowers",33,3,3,"painting.minecraft.sunflowers.title","painting.minecraft.sunflowers.author"),
        SEA = new Painting("minecraft:sea",34,1,2,"painting.minecraft.sea.title","painting.minecraft.sea.author"),
        WANDERER = new Painting("minecraft:wanderer",35,2,1,"painting.minecraft.wanderer.title","painting.minecraft.wanderer.author"),
        BACKYARD = new Painting("minecraft:backyard",36,4,3,"painting.minecraft.backyard.title","painting.minecraft.backyard.author"),
        BUST = new Painting("minecraft:bust",37,2,2,"painting.minecraft.bust.title","painting.minecraft.bust.author"),
        ORB = new Painting("minecraft:orb",38,4,4,"painting.minecraft.orb.title","painting.minecraft.orb.author"),
        MATCH = new Painting("minecraft:match",39,2,2,"painting.minecraft.match.title","painting.minecraft.match.author"),
        AZTEC2 = new Painting("minecraft:aztec2",40,1,1,"painting.minecraft.aztec2.title","painting.minecraft.aztec2.author"),
        TIDES = new Painting("minecraft:tides",41,3,3,"painting.minecraft.tides.title","painting.minecraft.tides.author"),
        COURBET = new Painting("minecraft:courbet",42,1,2,"painting.minecraft.courbet.title","painting.minecraft.courbet.author"),
        ENDBOSS = new Painting("minecraft:endboss",43,3,3,"painting.minecraft.endboss.title","painting.minecraft.endboss.author"),
        STAGE = new Painting("minecraft:stage",44,2,2,"painting.minecraft.stage.title","painting.minecraft.stage.author"),
        EARTH = new Painting("minecraft:earth",45,2,2,"painting.minecraft.earth.title",null),
        SUNSET = new Painting("minecraft:sunset",46,1,2,"painting.minecraft.sunset.title","painting.minecraft.sunset.author"),
        KEBAB = new Painting("minecraft:kebab",47,1,1,"painting.minecraft.kebab.title","painting.minecraft.kebab.author"),
        WITHER = new Painting("minecraft:wither",48,2,2,"painting.minecraft.wither.title",null),
        OWLEMONS = new Painting("minecraft:owlemons",49,3,3,"painting.minecraft.owlemons.title","painting.minecraft.owlemons.author");
}