package dev.hypix.reactor.api.world.block;

/* Autogenerated - Don't touch :) */
public final class Painting {

    public static final Painting[] ALL = new Painting[50];

    private final String id;
    private final int height;
    private final int width;

    public Painting(final String id, int height, int width) {
        this.id = id;
        this.height = height;
        this.width = width;
    }

    private Painting(final String id, int height, int width, int index) {
        this(id, height, width);
        ALL[index] = this;
    }

    public String getId() {
        return id;
    }

    public int getHeight() {
        return height;
    }

    public int getWidth() {
        return width;
    }

    public static final Painting
        ALBAN = new Painting("minecraft:alban",1,1,0),
        AZTEC = new Painting("minecraft:aztec",1,1,1),
        AZTEC2 = new Painting("minecraft:aztec2",1,1,2),
        BACKYARD = new Painting("minecraft:backyard",4,3,3),
        BAROQUE = new Painting("minecraft:baroque",2,2,4),
        BOMB = new Painting("minecraft:bomb",1,1,5),
        BOUQUET = new Painting("minecraft:bouquet",3,3,6),
        BURNING_SKULL = new Painting("minecraft:burning_skull",4,4,7),
        BUST = new Painting("minecraft:bust",2,2,8),
        CAVEBIRD = new Painting("minecraft:cavebird",3,3,9),
        CHANGING = new Painting("minecraft:changing",2,4,10),
        COTAN = new Painting("minecraft:cotan",3,3,11),
        COURBET = new Painting("minecraft:courbet",1,2,12),
        CREEBET = new Painting("minecraft:creebet",1,2,13),
        DONKEY_KONG = new Painting("minecraft:donkey_kong",3,4,14),
        EARTH = new Painting("minecraft:earth",2,2,15),
        ENDBOSS = new Painting("minecraft:endboss",3,3,16),
        FERN = new Painting("minecraft:fern",3,3,17),
        FIGHTERS = new Painting("minecraft:fighters",2,4,18),
        FINDING = new Painting("minecraft:finding",2,4,19),
        FIRE = new Painting("minecraft:fire",2,2,20),
        GRAHAM = new Painting("minecraft:graham",2,1,21),
        HUMBLE = new Painting("minecraft:humble",2,2,22),
        KEBAB = new Painting("minecraft:kebab",1,1,23),
        LOWMIST = new Painting("minecraft:lowmist",2,4,24),
        MATCH = new Painting("minecraft:match",2,2,25),
        MEDITATIVE = new Painting("minecraft:meditative",1,1,26),
        ORB = new Painting("minecraft:orb",4,4,27),
        OWLEMONS = new Painting("minecraft:owlemons",3,3,28),
        PASSAGE = new Painting("minecraft:passage",2,4,29),
        PIGSCENE = new Painting("minecraft:pigscene",4,4,30),
        PLANT = new Painting("minecraft:plant",1,1,31),
        POINTER = new Painting("minecraft:pointer",4,4,32),
        POND = new Painting("minecraft:pond",4,3,33),
        POOL = new Painting("minecraft:pool",1,2,34),
        PRAIRIE_RIDE = new Painting("minecraft:prairie_ride",2,1,35),
        SEA = new Painting("minecraft:sea",1,2,36),
        SKELETON = new Painting("minecraft:skeleton",3,4,37),
        SKULL_AND_ROSES = new Painting("minecraft:skull_and_roses",2,2,38),
        STAGE = new Painting("minecraft:stage",2,2,39),
        SUNFLOWERS = new Painting("minecraft:sunflowers",3,3,40),
        SUNSET = new Painting("minecraft:sunset",1,2,41),
        TIDES = new Painting("minecraft:tides",3,3,42),
        UNPACKED = new Painting("minecraft:unpacked",4,4,43),
        VOID = new Painting("minecraft:void",2,2,44),
        WANDERER = new Painting("minecraft:wanderer",2,1,45),
        WASTELAND = new Painting("minecraft:wasteland",1,1,46),
        WATER = new Painting("minecraft:water",2,2,47),
        WIND = new Painting("minecraft:wind",2,2,48),
        WITHER = new Painting("minecraft:wither",2,2,49);
}