package dev.hypix.reactor.api.entity.wolf;

import lombok.Getter;

/* Autogenerated - Don't touch :) */
@Getter
public final class WolfType {

    public static final WolfType[] ALL = new WolfType[9];
    private final String id;
    private final String angryTexture, tameTexture, wildTexture;
    private final String biome;

    public WolfType(String id, String angryTexture, String tameTexture, String wildTexture, String biome) {
        this.id = id;
        this.angryTexture = angryTexture;
        this.tameTexture = tameTexture;
        this.wildTexture = wildTexture;
        this.biome = biome;
    }

    public WolfType(String id, String angryTexture, String tameTexture, String wildTexture, String biome, int index) {
        this(id, angryTexture, tameTexture, wildTexture, biome);
        ALL[index] = this;
    }

    public static final WolfType
        ASHEN = new WolfType("minecraft:ashen","minecraft:entity/wolf/wolf_ashen_angry","minecraft:entity/wolf/wolf_ashen_tame","minecraft:entity/wolf/wolf_ashen","minecraft:snowy_taiga",0),
        BLACK = new WolfType("minecraft:black","minecraft:entity/wolf/wolf_black_angry","minecraft:entity/wolf/wolf_black_tame","minecraft:entity/wolf/wolf_black","minecraft:old_growth_pine_taiga",1),
        CHESTNUT = new WolfType("minecraft:chestnut","minecraft:entity/wolf/wolf_chestnut_angry","minecraft:entity/wolf/wolf_chestnut_tame","minecraft:entity/wolf/wolf_chestnut","minecraft:old_growth_spruce_taiga",2),
        PALE = new WolfType("minecraft:pale","minecraft:entity/wolf/wolf_angry","minecraft:entity/wolf/wolf_tame","minecraft:entity/wolf/wolf","minecraft:taiga",3),
        RUSTY = new WolfType("minecraft:rusty","minecraft:entity/wolf/wolf_rusty_angry","minecraft:entity/wolf/wolf_rusty_tame","minecraft:entity/wolf/wolf_rusty","#minecraft:is_jungle",4),
        SNOWY = new WolfType("minecraft:snowy","minecraft:entity/wolf/wolf_snowy_angry","minecraft:entity/wolf/wolf_snowy_tame","minecraft:entity/wolf/wolf_snowy","minecraft:grove",5),
        SPOTTED = new WolfType("minecraft:spotted","minecraft:entity/wolf/wolf_spotted_angry","minecraft:entity/wolf/wolf_spotted_tame","minecraft:entity/wolf/wolf_spotted","#minecraft:is_savanna",6),
        STRIPED = new WolfType("minecraft:striped","minecraft:entity/wolf/wolf_striped_angry","minecraft:entity/wolf/wolf_striped_tame","minecraft:entity/wolf/wolf_striped","#minecraft:is_badlands",7),
        WOODS = new WolfType("minecraft:woods","minecraft:entity/wolf/wolf_woods_angry","minecraft:entity/wolf/wolf_woods_tame","minecraft:entity/wolf/wolf_woods","minecraft:forest",8);
}