/*
* Autogenerated file. Please don't touch :)
* Class generator: dev.hypix.dataparser.registry.wolf.WolfVariantParser (module data-parser)
* Date: Year: 2025. Month: 01. Day: 14. Time: 16:17:44
*/
package dev.hypix.reactor.api.entity.wolf;
import lombok.Getter;

import java.util.Collection;

import dev.hypix.reactor.api.util.collection.CopyOnWriteCollection;

@Getter
public final class WolfType {

    public static final Collection<WolfType> ALL = new CopyOnWriteCollection<>(9);

    private final String name;
    private final String angryTexture, tameTexture, wildTexture;

    public WolfType(String name, String angryTexture, String tameTexture, String wildTexture) {
        this.name = name;
        this.angryTexture = angryTexture;
        this.tameTexture = tameTexture;
        this.wildTexture = wildTexture;
    }

    private WolfType(String name, int index, String angryTexture, String tameTexture, String wildTexture) {
        this(name, angryTexture, tameTexture, wildTexture);
        ALL.add(this);
    }

    public static final WolfType 
        STRIPED = new WolfType("striped",0,"minecraft:entity/wolf/wolf_striped_angry","minecraft:entity/wolf/wolf_striped_tame","minecraft:entity/wolf/wolf_striped"),
        ASHEN = new WolfType("ashen",1,"minecraft:entity/wolf/wolf_ashen_angry","minecraft:entity/wolf/wolf_ashen_tame","minecraft:entity/wolf/wolf_ashen"),
        WOODS = new WolfType("woods",2,"minecraft:entity/wolf/wolf_woods_angry","minecraft:entity/wolf/wolf_woods_tame","minecraft:entity/wolf/wolf_woods"),
        RUSTY = new WolfType("rusty",3,"minecraft:entity/wolf/wolf_rusty_angry","minecraft:entity/wolf/wolf_rusty_tame","minecraft:entity/wolf/wolf_rusty"),
        BLACK = new WolfType("black",4,"minecraft:entity/wolf/wolf_black_angry","minecraft:entity/wolf/wolf_black_tame","minecraft:entity/wolf/wolf_black"),
        CHESTNUT = new WolfType("chestnut",5,"minecraft:entity/wolf/wolf_chestnut_angry","minecraft:entity/wolf/wolf_chestnut_tame","minecraft:entity/wolf/wolf_chestnut"),
        PALE = new WolfType("pale",6,"minecraft:entity/wolf/wolf_angry","minecraft:entity/wolf/wolf_tame","minecraft:entity/wolf/wolf"),
        SNOWY = new WolfType("snowy",7,"minecraft:entity/wolf/wolf_snowy_angry","minecraft:entity/wolf/wolf_snowy_tame","minecraft:entity/wolf/wolf_snowy"),
        SPOTTED = new WolfType("spotted",8,"minecraft:entity/wolf/wolf_spotted_angry","minecraft:entity/wolf/wolf_spotted_tame","minecraft:entity/wolf/wolf_spotted");
}