/*
* Autogenerated file. Please don't touch :)
* Class generator: dev.hypix.dataparser.registry.damage.DamageTypeParser (module data-parser)
* Date: Year: 2025. Month: 01. Day: 14. Time: 16:12:06
*/
package dev.hypix.reactor.api.entity.damage;
import lombok.Getter;

import java.util.Collection;

import dev.hypix.reactor.api.util.collection.CopyOnWriteCollection;

@Getter
public final class DamageType {

    public static final Collection<DamageType> ALL = new CopyOnWriteCollection<>(49);

    private final double exhaustion;
    private final String name, scaling, messageId;

    public DamageType(String name, double exhaustion, String messageId, String scaling) {
        this.name = name;
        this.exhaustion = exhaustion;
        this.messageId = messageId;
        this.scaling = scaling;
    }

    private DamageType(String name, int index, double exhaustion, String messageId, String scaling) {
        this(name, exhaustion, messageId, scaling);
        ALL.add(this);
    }

    public static final DamageType 
        DRAGON_BREATH = new DamageType("dragon_breath",0,0.0,"dragonBreath","when_caused_by_living_non_player"),
        MAGIC = new DamageType("magic",1,0.0,"magic","when_caused_by_living_non_player"),
        THORNS = new DamageType("thorns",2,0.1,"thorns","when_caused_by_living_non_player"),
        FALLING_ANVIL = new DamageType("falling_anvil",3,0.1,"anvil","when_caused_by_living_non_player"),
        ARROW = new DamageType("arrow",4,0.1,"arrow","when_caused_by_living_non_player"),
        DROWN = new DamageType("drown",5,0.0,"drown","when_caused_by_living_non_player"),
        OUT_OF_WORLD = new DamageType("out_of_world",6,0.0,"outOfWorld","when_caused_by_living_non_player"),
        PLAYER_ATTACK = new DamageType("player_attack",7,0.1,"player","when_caused_by_living_non_player"),
        MACE_SMASH = new DamageType("mace_smash",8,0.1,"mace_smash","when_caused_by_living_non_player"),
        FREEZE = new DamageType("freeze",9,0.0,"freeze","when_caused_by_living_non_player"),
        GENERIC_KILL = new DamageType("generic_kill",10,0.0,"genericKill","when_caused_by_living_non_player"),
        UNATTRIBUTED_FIREBALL = new DamageType("unattributed_fireball",11,0.1,"onFire","when_caused_by_living_non_player"),
        FALLING_STALACTITE = new DamageType("falling_stalactite",12,0.1,"fallingStalactite","when_caused_by_living_non_player"),
        CAMPFIRE = new DamageType("campfire",13,0.1,"inFire","when_caused_by_living_non_player"),
        IN_FIRE = new DamageType("in_fire",14,0.1,"inFire","when_caused_by_living_non_player"),
        INDIRECT_MAGIC = new DamageType("indirect_magic",15,0.0,"indirectMagic","when_caused_by_living_non_player"),
        STALAGMITE = new DamageType("stalagmite",16,0.0,"stalagmite","when_caused_by_living_non_player"),
        THROWN = new DamageType("thrown",17,0.1,"thrown","when_caused_by_living_non_player"),
        SONIC_BOOM = new DamageType("sonic_boom",18,0.0,"sonic_boom","always"),
        IN_WALL = new DamageType("in_wall",19,0.0,"inWall","when_caused_by_living_non_player"),
        HOT_FLOOR = new DamageType("hot_floor",20,0.1,"hotFloor","when_caused_by_living_non_player"),
        MOB_PROJECTILE = new DamageType("mob_projectile",21,0.1,"mob","when_caused_by_living_non_player"),
        LIGHTNING_BOLT = new DamageType("lightning_bolt",22,0.1,"lightningBolt","when_caused_by_living_non_player"),
        SWEET_BERRY_BUSH = new DamageType("sweet_berry_bush",23,0.1,"sweetBerryBush","when_caused_by_living_non_player"),
        STARVE = new DamageType("starve",24,0.0,"starve","when_caused_by_living_non_player"),
        FIREWORKS = new DamageType("fireworks",25,0.1,"fireworks","when_caused_by_living_non_player"),
        LAVA = new DamageType("lava",26,0.1,"lava","when_caused_by_living_non_player"),
        FALL = new DamageType("fall",27,0.0,"fall","when_caused_by_living_non_player"),
        MOB_ATTACK = new DamageType("mob_attack",28,0.1,"mob","when_caused_by_living_non_player"),
        CACTUS = new DamageType("cactus",29,0.1,"cactus","when_caused_by_living_non_player"),
        ENDER_PEARL = new DamageType("ender_pearl",30,0.0,"fall","when_caused_by_living_non_player"),
        WIND_CHARGE = new DamageType("wind_charge",31,0.1,"mob","when_caused_by_living_non_player"),
        PLAYER_EXPLOSION = new DamageType("player_explosion",32,0.1,"explosion.player","always"),
        FIREBALL = new DamageType("fireball",33,0.1,"fireball","when_caused_by_living_non_player"),
        MOB_ATTACK_NO_AGGRO = new DamageType("mob_attack_no_aggro",34,0.1,"mob","when_caused_by_living_non_player"),
        BAD_RESPAWN_POINT = new DamageType("bad_respawn_point",35,0.1,"badRespawnPoint","always"),
        TRIDENT = new DamageType("trident",36,0.1,"trident","when_caused_by_living_non_player"),
        CRAMMING = new DamageType("cramming",37,0.0,"cramming","when_caused_by_living_non_player"),
        WITHER_SKULL = new DamageType("wither_skull",38,0.1,"witherSkull","when_caused_by_living_non_player"),
        ON_FIRE = new DamageType("on_fire",39,0.0,"onFire","when_caused_by_living_non_player"),
        STING = new DamageType("sting",40,0.1,"sting","when_caused_by_living_non_player"),
        GENERIC = new DamageType("generic",41,0.0,"generic","when_caused_by_living_non_player"),
        FALLING_BLOCK = new DamageType("falling_block",42,0.1,"fallingBlock","when_caused_by_living_non_player"),
        EXPLOSION = new DamageType("explosion",43,0.1,"explosion","always"),
        OUTSIDE_BORDER = new DamageType("outside_border",44,0.0,"outsideBorder","when_caused_by_living_non_player"),
        DRY_OUT = new DamageType("dry_out",45,0.1,"dryout","when_caused_by_living_non_player"),
        FLY_INTO_WALL = new DamageType("fly_into_wall",46,0.0,"flyIntoWall","when_caused_by_living_non_player"),
        SPIT = new DamageType("spit",47,0.1,"mob","when_caused_by_living_non_player"),
        WITHER = new DamageType("wither",48,0.0,"wither","when_caused_by_living_non_player");
}