package dev.hypix.reactor.api.entity.damage;

import lombok.Getter;

/* Autogenerated - Don't touch :) */
@Getter
public final class DamageType {
    public static final DamageType[] ALL = new DamageType[47];

    private final String id;
    private final double exhaustion;
    private final String messageId;
    private final String scaling;
    private final String effect;

    public DamageType(String id, double exhaustion, String messageId, String scaling, String effect) {
        this.id = id;
        this.exhaustion = exhaustion;
        this.messageId = messageId;
        this.scaling = scaling;
        this.effect = effect;
    }

    private DamageType(String id, double exhaustion, String messageId, String scaling, int index) {
        this(id, exhaustion, messageId, scaling, "hurt");
        ALL[index] = this;
    }

    public static final DamageType
        ARROW = new DamageType("minecraft:arrow",0.10000000149011612,"arrow","when_caused_by_living_non_player",0),
        BAD_RESPAWN_POINT = new DamageType("minecraft:bad_respawn_point",0.10000000149011612,"badRespawnPoint","always",1),
        CACTUS = new DamageType("minecraft:cactus",0.10000000149011612,"cactus","when_caused_by_living_non_player",2),
        CAMPFIRE = new DamageType("minecraft:campfire",0.10000000149011612,"inFire","when_caused_by_living_non_player",3),
        CRAMMING = new DamageType("minecraft:cramming",0.0,"cramming","when_caused_by_living_non_player",4),
        DRAGON_BREATH = new DamageType("minecraft:dragon_breath",0.0,"dragonBreath","when_caused_by_living_non_player",5),
        DROWN = new DamageType("minecraft:drown",0.0,"drown","when_caused_by_living_non_player",6),
        DRY_OUT = new DamageType("minecraft:dry_out",0.10000000149011612,"dryout","when_caused_by_living_non_player",7),
        EXPLOSION = new DamageType("minecraft:explosion",0.10000000149011612,"explosion","always",8),
        FALL = new DamageType("minecraft:fall",0.0,"fall","when_caused_by_living_non_player",9),
        FALLING_ANVIL = new DamageType("minecraft:falling_anvil",0.10000000149011612,"anvil","when_caused_by_living_non_player",10),
        FALLING_BLOCK = new DamageType("minecraft:falling_block",0.10000000149011612,"fallingBlock","when_caused_by_living_non_player",11),
        FALLING_STALACTITE = new DamageType("minecraft:falling_stalactite",0.10000000149011612,"fallingStalactite","when_caused_by_living_non_player",12),
        FIREBALL = new DamageType("minecraft:fireball",0.10000000149011612,"fireball","when_caused_by_living_non_player",13),
        FIREWORKS = new DamageType("minecraft:fireworks",0.10000000149011612,"fireworks","when_caused_by_living_non_player",14),
        FLY_INTO_WALL = new DamageType("minecraft:fly_into_wall",0.0,"flyIntoWall","when_caused_by_living_non_player",15),
        FREEZE = new DamageType("minecraft:freeze",0.0,"freeze","when_caused_by_living_non_player",16),
        GENERIC = new DamageType("minecraft:generic",0.0,"generic","when_caused_by_living_non_player",17),
        GENERIC_KILL = new DamageType("minecraft:generic_kill",0.0,"genericKill","when_caused_by_living_non_player",18),
        HOT_FLOOR = new DamageType("minecraft:hot_floor",0.10000000149011612,"hotFloor","when_caused_by_living_non_player",19),
        IN_FIRE = new DamageType("minecraft:in_fire",0.10000000149011612,"inFire","when_caused_by_living_non_player",20),
        IN_WALL = new DamageType("minecraft:in_wall",0.0,"inWall","when_caused_by_living_non_player",21),
        INDIRECT_MAGIC = new DamageType("minecraft:indirect_magic",0.0,"indirectMagic","when_caused_by_living_non_player",22),
        LAVA = new DamageType("minecraft:lava",0.10000000149011612,"lava","when_caused_by_living_non_player",23),
        LIGHTNING_BOLT = new DamageType("minecraft:lightning_bolt",0.10000000149011612,"lightningBolt","when_caused_by_living_non_player",24),
        MAGIC = new DamageType("minecraft:magic",0.0,"magic","when_caused_by_living_non_player",25),
        MOB_ATTACK = new DamageType("minecraft:mob_attack",0.10000000149011612,"mob","when_caused_by_living_non_player",26),
        MOB_ATTACK_NO_AGGRO = new DamageType("minecraft:mob_attack_no_aggro",0.10000000149011612,"mob","when_caused_by_living_non_player",27),
        MOB_PROJECTILE = new DamageType("minecraft:mob_projectile",0.10000000149011612,"mob","when_caused_by_living_non_player",28),
        ON_FIRE = new DamageType("minecraft:on_fire",0.0,"onFire","when_caused_by_living_non_player",29),
        OUT_OF_WORLD = new DamageType("minecraft:out_of_world",0.0,"outOfWorld","when_caused_by_living_non_player",30),
        OUTSIDE_BORDER = new DamageType("minecraft:outside_border",0.0,"outsideBorder","when_caused_by_living_non_player",31),
        PLAYER_ATTACK = new DamageType("minecraft:player_attack",0.10000000149011612,"player","when_caused_by_living_non_player",32),
        PLAYER_EXPLOSION = new DamageType("minecraft:player_explosion",0.10000000149011612,"explosion.player","always",33),
        SONIC_BOOM = new DamageType("minecraft:sonic_boom",0.0,"sonic_boom","always",34),
        SPIT = new DamageType("minecraft:spit",0.10000000149011612,"mob","when_caused_by_living_non_player",35),
        STALAGMITE = new DamageType("minecraft:stalagmite",0.0,"stalagmite","when_caused_by_living_non_player",36),
        STARVE = new DamageType("minecraft:starve",0.0,"starve","when_caused_by_living_non_player",37),
        STING = new DamageType("minecraft:sting",0.10000000149011612,"sting","when_caused_by_living_non_player",38),
        SWEET_BERRY_BUSH = new DamageType("minecraft:sweet_berry_bush",0.10000000149011612,"sweetBerryBush","when_caused_by_living_non_player",39),
        THORNS = new DamageType("minecraft:thorns",0.10000000149011612,"thorns","when_caused_by_living_non_player",40),
        THROWN = new DamageType("minecraft:thrown",0.10000000149011612,"thrown","when_caused_by_living_non_player",41),
        TRIDENT = new DamageType("minecraft:trident",0.10000000149011612,"trident","when_caused_by_living_non_player",42),
        UNATTRIBUTED_FIREBALL = new DamageType("minecraft:unattributed_fireball",0.10000000149011612,"onFire","when_caused_by_living_non_player",43),
        WIND_CHARGE = new DamageType("minecraft:wind_charge",0.10000000149011612,"mob","when_caused_by_living_non_player",44),
        WITHER = new DamageType("minecraft:wither",0.0,"wither","when_caused_by_living_non_player",45),
        WITHER_SKULL = new DamageType("minecraft:wither_skull",0.10000000149011612,"witherSkull","when_caused_by_living_non_player",46);
}