/*
* Autogenerated file. Please don't touch :)
* Class generator: dev.hypix.dataparser.registry.enchantment.EnchantmentParser (module data-parser)
* Date: Year: 2025. Month: 01. Day: 14. Time: 16:13:20
*/
package dev.hypix.reactor.api.item.enchantment;

import lombok.Getter;

import java.util.Collection;
import dev.hypix.reactor.api.util.collection.CopyOnWriteCollection;

@Getter
public final class Enchantment {

    public static final Collection<Enchantment> ALL = new CopyOnWriteCollection<>(42);

    private final int id, maxLevel;
    private final String name;

    public Enchantment(String name, int id, int maxLevel) {
        this.name = name;
        this.id = id;
        this.maxLevel = maxLevel;
    }

    private Enchantment(int id, String name, int maxLevel) {
        this(name, id, maxLevel);
        ALL.add(this);
    }

    @Override
    public int hashCode() {
        return id;
    }

    @Override
    public boolean equals(final Object object) {
        return object == this || (object instanceof Enchantment enchantment && enchantment.id == this.id);
    }

    public static final Enchantment 
        AQUA_AFFINITY = new Enchantment(0,"aqua_affinity",1),
        BANE_OF_ARTHROPODS = new Enchantment(1,"bane_of_arthropods",5),
        BINDING_CURSE = new Enchantment(2,"binding_curse",1),
        BLAST_PROTECTION = new Enchantment(3,"blast_protection",4),
        BREACH = new Enchantment(4,"breach",4),
        CHANNELING = new Enchantment(5,"channeling",1),
        DENSITY = new Enchantment(6,"density",5),
        DEPTH_STRIDER = new Enchantment(7,"depth_strider",3),
        EFFICIENCY = new Enchantment(8,"efficiency",5),
        FEATHER_FALLING = new Enchantment(9,"feather_falling",4),
        FIRE_ASPECT = new Enchantment(10,"fire_aspect",2),
        FIRE_PROTECTION = new Enchantment(11,"fire_protection",4),
        FLAME = new Enchantment(12,"flame",1),
        FORTUNE = new Enchantment(13,"fortune",3),
        FROST_WALKER = new Enchantment(14,"frost_walker",2),
        IMPALING = new Enchantment(15,"impaling",5),
        INFINITY = new Enchantment(16,"infinity",1),
        KNOCKBACK = new Enchantment(17,"knockback",2),
        LOOTING = new Enchantment(18,"looting",3),
        LOYALTY = new Enchantment(19,"loyalty",3),
        LUCK_OF_THE_SEA = new Enchantment(20,"luck_of_the_sea",3),
        LURE = new Enchantment(21,"lure",3),
        MENDING = new Enchantment(22,"mending",1),
        MULTISHOT = new Enchantment(23,"multishot",1),
        PIERCING = new Enchantment(24,"piercing",4),
        POWER = new Enchantment(25,"power",5),
        PROJECTILE_PROTECTION = new Enchantment(26,"projectile_protection",4),
        PROTECTION = new Enchantment(27,"protection",4),
        PUNCH = new Enchantment(28,"punch",2),
        QUICK_CHARGE = new Enchantment(29,"quick_charge",3),
        RESPIRATION = new Enchantment(30,"respiration",3),
        RIPTIDE = new Enchantment(31,"riptide",3),
        SHARPNESS = new Enchantment(32,"sharpness",5),
        SILK_TOUCH = new Enchantment(33,"silk_touch",1),
        SMITE = new Enchantment(34,"smite",5),
        SOUL_SPEED = new Enchantment(35,"soul_speed",3),
        SWEEPING_EDGE = new Enchantment(36,"sweeping_edge",3),
        SWIFT_SNEAK = new Enchantment(37,"swift_sneak",3),
        THORNS = new Enchantment(38,"thorns",3),
        UNBREAKING = new Enchantment(39,"unbreaking",3),
        VANISHING_CURSE = new Enchantment(40,"vanishing_curse",1),
        WIND_BURST = new Enchantment(41,"wind_burst",3);
}