package dev.hypix.reactor.api.item.armor;

import lombok.Getter;

/* Autogenerated - Don't touch :) */
@Getter
public final class TrimPattern {

    public static final TrimPattern[] ALL = new TrimPattern[18];
    private final String id;
    private final String description;
    private final String item;

    public TrimPattern(String id, String description, String item) {
        this.id = id;
        this.description = description;
        this.item = item;
    }

    private TrimPattern(String id, String description, String item, int index) {
        this(id, description, item);
        ALL[index] = this;
    }

    public static final TrimPattern
        BOLT = new TrimPattern("minecraft:bolt","trim_pattern.minecraft.bolt","minecraft:bolt_armor_trim_smithing_template",0),
        COAST = new TrimPattern("minecraft:coast","trim_pattern.minecraft.coast","minecraft:coast_armor_trim_smithing_template",1),
        DUNE = new TrimPattern("minecraft:dune","trim_pattern.minecraft.dune","minecraft:dune_armor_trim_smithing_template",2),
        EYE = new TrimPattern("minecraft:eye","trim_pattern.minecraft.eye","minecraft:eye_armor_trim_smithing_template",3),
        FLOW = new TrimPattern("minecraft:flow","trim_pattern.minecraft.flow","minecraft:flow_armor_trim_smithing_template",4),
        HOST = new TrimPattern("minecraft:host","trim_pattern.minecraft.host","minecraft:host_armor_trim_smithing_template",5),
        RAISER = new TrimPattern("minecraft:raiser","trim_pattern.minecraft.raiser","minecraft:raiser_armor_trim_smithing_template",6),
        RIB = new TrimPattern("minecraft:rib","trim_pattern.minecraft.rib","minecraft:rib_armor_trim_smithing_template",7),
        SENTRY = new TrimPattern("minecraft:sentry","trim_pattern.minecraft.sentry","minecraft:sentry_armor_trim_smithing_template",8),
        SHAPER = new TrimPattern("minecraft:shaper","trim_pattern.minecraft.shaper","minecraft:shaper_armor_trim_smithing_template",9),
        SILENCE = new TrimPattern("minecraft:silence","trim_pattern.minecraft.silence","minecraft:silence_armor_trim_smithing_template",10),
        SNOUT = new TrimPattern("minecraft:snout","trim_pattern.minecraft.snout","minecraft:snout_armor_trim_smithing_template",11),
        SPIRE = new TrimPattern("minecraft:spire","trim_pattern.minecraft.spire","minecraft:spire_armor_trim_smithing_template",12),
        TIDE = new TrimPattern("minecraft:tide","trim_pattern.minecraft.tide","minecraft:tide_armor_trim_smithing_template",13),
        VEX = new TrimPattern("minecraft:vex","trim_pattern.minecraft.vex","minecraft:vex_armor_trim_smithing_template",14),
        WARD = new TrimPattern("minecraft:ward","trim_pattern.minecraft.ward","minecraft:ward_armor_trim_smithing_template",15),
        WAYFINDER = new TrimPattern("minecraft:wayfinder","trim_pattern.minecraft.wayfinder","minecraft:wayfinder_armor_trim_smithing_template",16),
        WILD = new TrimPattern("minecraft:wild","trim_pattern.minecraft.wild","minecraft:wild_armor_trim_smithing_template",17);
}