package dev.hypix.dataparser.sound;

import java.util.Set;

import com.alibaba.fastjson2.JSONObject;

import dev.hypix.dataparser.Parser;

public final class SoundParser implements Parser {

    @Override
    public String requiredFile() {
        return "sounds.json";
    }

    public ParsedFile parse(final JSONObject json) {
        final Set<String> sounds = json.keySet();
        final StringBuilder builder = new StringBuilder();

        builder.append(
            """
            package dev.hypix.dataparser.sound;

            /* Autogenerated - Don't touch :) */
            public final class MinecraftSound {

                public static final String[] ALL = new String[%amount%];
    
                private static String of(final String sound, final int index) {
                    ALL[index] = sound;
                    return sound;
                }

                public static final String
            """.replaceFirst("%amount%", String.valueOf(sounds.size()))
        );

        int i = 0;
        for (final String sound : sounds) {
            builder.append("        ");
            final String fieldName = sound.toUpperCase().replace('.', '_');
            final int index = fieldName.indexOf('_');
            builder.append((index == -1) ? fieldName : fieldName.substring(index+1));
    
            builder.append("=of(\"minecraft:");
            builder.append(sound);
            builder.append('"');
            builder.append(',');
            builder.append(i);
            builder.append(')');

            if (++i == sounds.size()) {
                builder.append(';');
            } else {
                builder.append(',');
            }
            builder.append('\n');
        }

        builder.append('}');
    
        return new ParsedFile("sound/MinecraftSound.java", builder.toString());
    }
}
