/*
* Autogenerated file. Please don't touch :)
* Class generator: dev.hypix.dataparser.registry.chat.ChatParser (module data-parser)
* Date: Year: 2025. Month: 01. Day: 14. Time: 16:11:04
*/
package dev.hypix.reactor.api.chat;
import lombok.Getter;

import java.util.Collection;

import dev.hypix.reactor.api.util.collection.CopyOnWriteCollection;

@Getter
public final class ChatType {
    public static final Collection<ChatType> ALL = new CopyOnWriteCollection<>(7);

    private static final String[] SENDER_CONTENT = new String[] {"sender", "content"};
    private static final String[] TARGET_SENDER_CONTENT = new String[] {"target","sender","content"};
    private final Data chat, narration;
    private final String name;

    private ChatType(String name, int index, Data chat, Data narration) {
        this.name = name;
        this.chat = chat;
        this.narration = narration;
        ALL.add(this);
    }

    public static final record Data(
        String[] parameters,
        String translationKey
    ){}

    public static final ChatType 
        CHAT = new ChatType("chat",0,new Data(SENDER_CONTENT,"chat.type.text"),new Data(SENDER_CONTENT,"chat.type.text.narrate")),
        MSG_COMMAND_OUTGOING = new ChatType("msg_command_outgoing",1,new Data(new String[] {"target","content"},"commands.message.display.outgoing"),new Data(SENDER_CONTENT,"chat.type.text.narrate")),
        TEAM_MSG_COMMAND_OUTGOING = new ChatType("team_msg_command_outgoing",2,new Data(TARGET_SENDER_CONTENT,"chat.type.team.sent"),new Data(SENDER_CONTENT,"chat.type.text.narrate")),
        TEAM_MSG_COMMAND_INCOMING = new ChatType("team_msg_command_incoming",3,new Data(TARGET_SENDER_CONTENT,"chat.type.team.text"),new Data(SENDER_CONTENT,"chat.type.text.narrate")),
        SAY_COMMAND = new ChatType("say_command",4,new Data(SENDER_CONTENT,"chat.type.announcement"),new Data(SENDER_CONTENT,"chat.type.text.narrate")),
        MSG_COMMAND_INCOMING = new ChatType("msg_command_incoming",5,new Data(SENDER_CONTENT,"commands.message.display.incoming"),new Data(SENDER_CONTENT,"chat.type.text.narrate")),
        EMOTE_COMMAND = new ChatType("emote_command",6,new Data(SENDER_CONTENT,"chat.type.emote"),new Data(SENDER_CONTENT,"chat.type.emote"));
}