package dev.hypix.reactor.api.chat;

import lombok.Getter;

/* Autogenerated - Don't touch :) */
@Getter
public final class ChatType {

    public static final ChatType[] ALL = new ChatType[7];
    private final Data chat, narration;
    private final String id;

    public ChatType(String id, Data chat, Data narration) {
        this.id = id;
        this.chat = chat;
        this.narration = narration;
    }

    private ChatType(String id, Data chat, Data narration, int index) {
        this.id = id;
        this.chat = chat;
        this.narration = narration;
        ALL[index] = this;
    }

    public static final record Data(
        String[] parameters,
        String translationKey
    ){}

    public static final ChatType
        EMOTE_COMMAND = new ChatType("minecraft:emote_command",new ChatType.Data(new String[] {"sender","content"},"chat.type.emote"),new ChatType.Data(new String[] {"sender","content"},"chat.type.emote"),0),
        TEAM_MSG_COMMAND_INCOMING = new ChatType("minecraft:team_msg_command_incoming",new ChatType.Data(new String[] {"target","sender","content"},"chat.type.team.text"),new ChatType.Data(new String[] {"sender","content"},"chat.type.text.narrate"),1),
        TEAM_MSG_COMMAND_OUTGOING = new ChatType("minecraft:team_msg_command_outgoing",new ChatType.Data(new String[] {"target","sender","content"},"chat.type.team.sent"),new ChatType.Data(new String[] {"sender","content"},"chat.type.text.narrate"),2),
        CHAT = new ChatType("minecraft:chat",new ChatType.Data(new String[] {"sender","content"},"chat.type.text"),new ChatType.Data(new String[] {"sender","content"},"chat.type.text.narrate"),3),
        MSG_COMMAND_INCOMING = new ChatType("minecraft:msg_command_incoming",new ChatType.Data(new String[] {"sender","content"},"commands.message.display.incoming"),new ChatType.Data(new String[] {"sender","content"},"chat.type.text.narrate"),4),
        MSG_COMMAND_OUTGOING = new ChatType("minecraft:msg_command_outgoing",new ChatType.Data(new String[] {"target","content"},"commands.message.display.outgoing"),new ChatType.Data(new String[] {"sender","content"},"chat.type.text.narrate"),5),
        SAY_COMMAND = new ChatType("minecraft:say_command",new ChatType.Data(new String[] {"sender","content"},"chat.type.announcement"),new ChatType.Data(new String[] {"sender","content"},"chat.type.text.narrate"),6);
}