package dev.hypix.reactor.api.world.data;

import lombok.Getter;

/* Autogenerated - Don't touch :) */
@Getter
public final class Biome {

    public static final Biome[] ALL = new Biome[64];

    private final String id;
    private final double downFall;
    private final boolean hasPrecipitation;
    private final double temperature;
    private final Effects effects;

    public Biome(String id, double downFall, boolean hasPrecipitation, double temperature, Effects effects) {
        this.id = id;
        this.downFall = downFall;
        this.hasPrecipitation = hasPrecipitation;
        this.temperature = temperature;
        this.effects = effects;
    }

    private Biome(String id, double downFall, boolean hasPrecipitation, double temperature, Effects effects, int index) {
        this(id, downFall, hasPrecipitation, temperature, effects);
        ALL[index] = this;
    }

    public static record Effects(
        int fogColor,
        Integer foliageColor,
        Integer grassColor,
        String grassColorModifier,
        String ambientSound,
        int skyColor,
        int waterColor,
        int waterFogColor,
        MoodSound moodSound,
        Music music,
        AdditionSound additionSound,
        Particle particle
    ){

        public static record MoodSound(
            String sound,
            int tickDelay,
            int blockSearchExtent,
            double offSet
        ){}

        public static record Music(
            int maxDelay,
            int minDelay,
            boolean replaceCurrentMusic,
            String sound
        ){}

        public static record AdditionSound(
            String sound,
            double tickChance
        ){}

        public static record Particle(
            String type,
            double probability
        ){}
    }

    public static final Biome
        BADLANDS = new Biome("minecraft:badlands",0.0,false,2.0,new Effects(12638463,10387789,9470285,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.badlands"),null,null),0),
        BAMBOO_JUNGLE = new Biome("minecraft:bamboo_jungle",0.8999999761581421,true,0.949999988079071,new Effects(12638463,null,null,null,null,7842047,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.bamboo_jungle"),null,null),1),
        BASALT_DELTAS = new Biome("minecraft:basalt_deltas",0.0,false,2.0,new Effects(6840176,null,null,null,"minecraft:ambient.basalt_deltas.loop",7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.basalt_deltas.mood",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.nether.basalt_deltas"),new Effects.AdditionSound("minecraft:ambient.basalt_deltas.additions",0.0111),new Effects.Particle("minecraft:white_ash",0.118093334)),2),
        BEACH = new Biome("minecraft:beach",0.4000000059604645,true,0.800000011920929,new Effects(12638463,null,null,null,null,7907327,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),3),
        BIRCH_FOREST = new Biome("minecraft:birch_forest",0.6000000238418579,true,0.6000000238418579,new Effects(12638463,null,null,null,null,8037887,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.forest"),null,null),4),
        CHERRY_GROVE = new Biome("minecraft:cherry_grove",0.800000011920929,true,0.5,new Effects(12638463,11983713,11983713,null,null,8103167,6141935,6141935,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.cherry_grove"),null,null),5),
        COLD_OCEAN = new Biome("minecraft:cold_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4020182,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),6),
        CRIMSON_FOREST = new Biome("minecraft:crimson_forest",0.0,false,2.0,new Effects(3343107,null,null,null,"minecraft:ambient.crimson_forest.loop",7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.crimson_forest.mood",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.nether.crimson_forest"),new Effects.AdditionSound("minecraft:ambient.crimson_forest.additions",0.0111),new Effects.Particle("minecraft:crimson_spore",0.025)),7),
        DARK_FOREST = new Biome("minecraft:dark_forest",0.800000011920929,true,0.699999988079071,new Effects(12638463,null,null,"dark_forest",null,7972607,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.forest"),null,null),8),
        DEEP_COLD_OCEAN = new Biome("minecraft:deep_cold_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4020182,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),9),
        DEEP_DARK = new Biome("minecraft:deep_dark",0.4000000059604645,true,0.800000011920929,new Effects(12638463,null,null,null,null,7907327,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.deep_dark"),null,null),10),
        DEEP_FROZEN_OCEAN = new Biome("minecraft:deep_frozen_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,3750089,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),11),
        DEEP_LUKEWARM_OCEAN = new Biome("minecraft:deep_lukewarm_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4566514,267827,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),12),
        DEEP_OCEAN = new Biome("minecraft:deep_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),13),
        DESERT = new Biome("minecraft:desert",0.0,false,2.0,new Effects(12638463,null,null,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.desert"),null,null),14),
        DRIPSTONE_CAVES = new Biome("minecraft:dripstone_caves",0.4000000059604645,true,0.800000011920929,new Effects(12638463,null,null,null,null,7907327,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.dripstone_caves"),null,null),15),
        END_BARRENS = new Biome("minecraft:end_barrens",0.5,false,0.5,new Effects(10518688,null,null,null,null,0,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),16),
        END_HIGHLANDS = new Biome("minecraft:end_highlands",0.5,false,0.5,new Effects(10518688,null,null,null,null,0,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),17),
        END_MIDLANDS = new Biome("minecraft:end_midlands",0.5,false,0.5,new Effects(10518688,null,null,null,null,0,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),18),
        ERODED_BADLANDS = new Biome("minecraft:eroded_badlands",0.0,false,2.0,new Effects(12638463,10387789,9470285,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.badlands"),null,null),19),
        FLOWER_FOREST = new Biome("minecraft:flower_forest",0.800000011920929,true,0.699999988079071,new Effects(12638463,null,null,null,null,7972607,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.flower_forest"),null,null),20),
        FOREST = new Biome("minecraft:forest",0.800000011920929,true,0.699999988079071,new Effects(12638463,null,null,null,null,7972607,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.forest"),null,null),21),
        FROZEN_OCEAN = new Biome("minecraft:frozen_ocean",0.5,true,0.0,new Effects(12638463,null,null,null,null,8364543,3750089,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),22),
        FROZEN_PEAKS = new Biome("minecraft:frozen_peaks",0.8999999761581421,true,-0.699999988079071,new Effects(12638463,null,null,null,null,8756735,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.frozen_peaks"),null,null),23),
        FROZEN_RIVER = new Biome("minecraft:frozen_river",0.5,true,0.0,new Effects(12638463,null,null,null,null,8364543,3750089,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),24),
        GROVE = new Biome("minecraft:grove",0.800000011920929,true,-0.20000000298023224,new Effects(12638463,null,null,null,null,8495359,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.grove"),null,null),25),
        ICE_SPIKES = new Biome("minecraft:ice_spikes",0.5,true,0.0,new Effects(12638463,null,null,null,null,8364543,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),26),
        JAGGED_PEAKS = new Biome("minecraft:jagged_peaks",0.8999999761581421,true,-0.699999988079071,new Effects(12638463,null,null,null,null,8756735,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.jagged_peaks"),null,null),27),
        JUNGLE = new Biome("minecraft:jungle",0.8999999761581421,true,0.949999988079071,new Effects(12638463,null,null,null,null,7842047,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.jungle"),null,null),28),
        LUKEWARM_OCEAN = new Biome("minecraft:lukewarm_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4566514,267827,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),29),
        LUSH_CAVES = new Biome("minecraft:lush_caves",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.lush_caves"),null,null),30),
        MANGROVE_SWAMP = new Biome("minecraft:mangrove_swamp",0.8999999761581421,true,0.800000011920929,new Effects(12638463,9285927,null,"swamp",null,7907327,3832426,5077600,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.swamp"),null,null),31),
        MEADOW = new Biome("minecraft:meadow",0.800000011920929,true,0.5,new Effects(12638463,null,null,null,null,8103167,937679,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.meadow"),null,null),32),
        MUSHROOM_FIELDS = new Biome("minecraft:mushroom_fields",1.0,true,0.8999999761581421,new Effects(12638463,null,null,null,null,7842047,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),33),
        NETHER_WASTES = new Biome("minecraft:nether_wastes",0.0,false,2.0,new Effects(3344392,null,null,null,"minecraft:ambient.nether_wastes.loop",7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.nether_wastes.mood",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.nether.nether_wastes"),new Effects.AdditionSound("minecraft:ambient.nether_wastes.additions",0.0111),null),34),
        OCEAN = new Biome("minecraft:ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),35),
        OLD_GROWTH_BIRCH_FOREST = new Biome("minecraft:old_growth_birch_forest",0.6000000238418579,true,0.6000000238418579,new Effects(12638463,null,null,null,null,8037887,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.forest"),null,null),36),
        OLD_GROWTH_PINE_TAIGA = new Biome("minecraft:old_growth_pine_taiga",0.800000011920929,true,0.30000001192092896,new Effects(12638463,null,null,null,null,8168447,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.old_growth_taiga"),null,null),37),
        OLD_GROWTH_SPRUCE_TAIGA = new Biome("minecraft:old_growth_spruce_taiga",0.800000011920929,true,0.25,new Effects(12638463,null,null,null,null,8233983,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.old_growth_taiga"),null,null),38),
        PLAINS = new Biome("minecraft:plains",0.4000000059604645,true,0.800000011920929,new Effects(12638463,null,null,null,null,7907327,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),39),
        RIVER = new Biome("minecraft:river",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),40),
        SAVANNA = new Biome("minecraft:savanna",0.0,false,2.0,new Effects(12638463,null,null,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),41),
        SAVANNA_PLATEAU = new Biome("minecraft:savanna_plateau",0.0,false,2.0,new Effects(12638463,null,null,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),42),
        SMALL_END_ISLANDS = new Biome("minecraft:small_end_islands",0.5,false,0.5,new Effects(10518688,null,null,null,null,0,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),43),
        SNOWY_BEACH = new Biome("minecraft:snowy_beach",0.30000001192092896,true,0.05000000074505806,new Effects(12638463,null,null,null,null,8364543,4020182,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),44),
        SNOWY_PLAINS = new Biome("minecraft:snowy_plains",0.5,true,0.0,new Effects(12638463,null,null,null,null,8364543,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),45),
        SNOWY_SLOPES = new Biome("minecraft:snowy_slopes",0.8999999761581421,true,-0.30000001192092896,new Effects(12638463,null,null,null,null,8560639,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.snowy_slopes"),null,null),46),
        SNOWY_TAIGA = new Biome("minecraft:snowy_taiga",0.4000000059604645,true,-0.5,new Effects(12638463,null,null,null,null,8625919,4020182,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),47),
        SOUL_SAND_VALLEY = new Biome("minecraft:soul_sand_valley",0.0,false,2.0,new Effects(1787717,null,null,null,"minecraft:ambient.soul_sand_valley.loop",7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.soul_sand_valley.mood",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.nether.soul_sand_valley"),new Effects.AdditionSound("minecraft:ambient.soul_sand_valley.additions",0.0111),new Effects.Particle("minecraft:ash",0.00625)),48),
        SPARSE_JUNGLE = new Biome("minecraft:sparse_jungle",0.800000011920929,true,0.949999988079071,new Effects(12638463,null,null,null,null,7842047,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.sparse_jungle"),null,null),49),
        STONY_PEAKS = new Biome("minecraft:stony_peaks",0.30000001192092896,true,1.0,new Effects(12638463,null,null,null,null,7776511,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.stony_peaks"),null,null),50),
        STONY_SHORE = new Biome("minecraft:stony_shore",0.30000001192092896,true,0.20000000298023224,new Effects(12638463,null,null,null,null,8233727,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),51),
        SUNFLOWER_PLAINS = new Biome("minecraft:sunflower_plains",0.4000000059604645,true,0.800000011920929,new Effects(12638463,null,null,null,null,7907327,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),52),
        SWAMP = new Biome("minecraft:swamp",0.8999999761581421,true,0.800000011920929,new Effects(12638463,6975545,null,"swamp",null,7907327,6388580,2302743,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.swamp"),null,null),53),
        TAIGA = new Biome("minecraft:taiga",0.800000011920929,true,0.25,new Effects(12638463,null,null,null,null,8233983,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),54),
        THE_END = new Biome("minecraft:the_end",0.5,false,0.5,new Effects(10518688,null,null,null,null,0,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),55),
        THE_VOID = new Biome("minecraft:the_void",0.5,false,0.5,new Effects(12638463,null,null,null,null,8103167,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),56),
        WARM_OCEAN = new Biome("minecraft:warm_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4445678,270131,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),57),
        WARPED_FOREST = new Biome("minecraft:warped_forest",0.0,false,2.0,new Effects(1705242,null,null,null,"minecraft:ambient.warped_forest.loop",7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.warped_forest.mood",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.nether.warped_forest"),new Effects.AdditionSound("minecraft:ambient.warped_forest.additions",0.0111),new Effects.Particle("minecraft:warped_spore",0.01428)),58),
        WINDSWEPT_FOREST = new Biome("minecraft:windswept_forest",0.30000001192092896,true,0.20000000298023224,new Effects(12638463,null,null,null,null,8233727,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),59),
        WINDSWEPT_GRAVELLY_HILLS = new Biome("minecraft:windswept_gravelly_hills",0.30000001192092896,true,0.20000000298023224,new Effects(12638463,null,null,null,null,8233727,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),60),
        WINDSWEPT_HILLS = new Biome("minecraft:windswept_hills",0.30000001192092896,true,0.20000000298023224,new Effects(12638463,null,null,null,null,8233727,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),61),
        WINDSWEPT_SAVANNA = new Biome("minecraft:windswept_savanna",0.0,false,2.0,new Effects(12638463,null,null,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null),62),
        WOODED_BADLANDS = new Biome("minecraft:wooded_badlands",0.0,false,2.0,new Effects(12638463,10387789,9470285,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),new Effects.Music(24000,12000,false,"minecraft:music.overworld.badlands"),null,null),63);
}