/*
* Autogenerated file. Please don't touch :)
* Class generator: dev.hypix.dataparser.registry.biome.BiomeParser (module data-parser)
* Date: Year: 2025. Month: 01. Day: 14. Time: 16:10:17
*/
package dev.hypix.reactor.api.world.data;
import lombok.Getter;

import java.util.Collection;

import dev.hypix.reactor.api.util.collection.CopyOnWriteCollection;

@Getter
public final class Biome {

    public static final Collection<Biome> ALL = new CopyOnWriteCollection<>(65);

    private final int id;
    private final String identifier;
    private final double downFall;
    private final boolean hasPrecipitation;
    private final double temperature;
    private final Effects effects;

    public Biome(String identifier, double downFall, boolean hasPrecipitation, double temperature, Effects effects, int id) {
        this.id = id;
        this.identifier = identifier;
        this.downFall = downFall;
        this.hasPrecipitation = hasPrecipitation;
        this.temperature = temperature;
        this.effects = effects;
    }

    private Biome(int id, String identifier, double downFall, boolean hasPrecipitation, double temperature, Effects effects) {
        this(identifier, downFall, hasPrecipitation, temperature, effects, id);
        ALL.add(this);
    }

    public static record Effects(
        int fogColor,
        Integer foliageColor,
        Integer grassColor,
        String grassColorModifier,
        String ambientSound,
        int skyColor,
        int waterColor,
        int waterFogColor,
        MoodSound moodSound,
        Music music,
        AdditionSound additionSound,
        Particle particle
    ){

        public static record MoodSound(
            String sound,
            int tickDelay,
            int blockSearchExtent,
            double offSet
        ){}

        public static record Music(
            int maxDelay,
            int minDelay,
            boolean replaceCurrentMusic,
            String sound
        ){}

        public static record AdditionSound(
            String sound,
            double tickChance
        ){}

        public static record Particle(
            String type,
            double probability
        ){}
    }

    public static final Biome 
        BADLANDS = new Biome(0,"badlands",0.0,false,2.0,new Effects(12638463,10387789,9470285,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        BAMBOO_JUNGLE = new Biome(1,"bamboo_jungle",0.9,true,0.95,new Effects(12638463,null,null,null,null,7842047,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        BASALT_DELTAS = new Biome(2,"basalt_deltas",0.0,false,2.0,new Effects(6840176,null,null,null,"minecraft:ambient.basalt_deltas.loop",7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.basalt_deltas.mood",6000,2,8),null,new Effects.AdditionSound("minecraft:ambient.basalt_deltas.additions",0.0111),new Effects.Particle("minecraft:white_ash",0.118093334))),
        BEACH = new Biome(3,"beach",0.4,true,0.8,new Effects(12638463,null,null,null,null,7907327,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        BIRCH_FOREST = new Biome(4,"birch_forest",0.6,true,0.6,new Effects(12638463,null,null,null,null,8037887,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        CHERRY_GROVE = new Biome(5,"cherry_grove",0.8,true,0.5,new Effects(12638463,11983713,11983713,null,null,8103167,6141935,6141935,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        COLD_OCEAN = new Biome(6,"cold_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4020182,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        CRIMSON_FOREST = new Biome(7,"crimson_forest",0.0,false,2.0,new Effects(3343107,null,null,null,"minecraft:ambient.crimson_forest.loop",7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.crimson_forest.mood",6000,2,8),null,new Effects.AdditionSound("minecraft:ambient.crimson_forest.additions",0.0111),new Effects.Particle("minecraft:crimson_spore",0.025))),
        DARK_FOREST = new Biome(8,"dark_forest",0.8,true,0.7,new Effects(12638463,null,null,"dark_forest",null,7972607,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        DEEP_COLD_OCEAN = new Biome(9,"deep_cold_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4020182,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        DEEP_DARK = new Biome(10,"deep_dark",0.4,true,0.8,new Effects(12638463,null,null,null,null,7907327,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        DEEP_FROZEN_OCEAN = new Biome(11,"deep_frozen_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,3750089,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        DEEP_LUKEWARM_OCEAN = new Biome(12,"deep_lukewarm_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4566514,267827,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        DEEP_OCEAN = new Biome(13,"deep_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        DESERT = new Biome(14,"desert",0.0,false,2.0,new Effects(12638463,null,null,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        DRIPSTONE_CAVES = new Biome(15,"dripstone_caves",0.4,true,0.8,new Effects(12638463,null,null,null,null,7907327,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        END_BARRENS = new Biome(16,"end_barrens",0.5,false,0.5,new Effects(10518688,null,null,null,null,0,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        END_HIGHLANDS = new Biome(17,"end_highlands",0.5,false,0.5,new Effects(10518688,null,null,null,null,0,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        END_MIDLANDS = new Biome(18,"end_midlands",0.5,false,0.5,new Effects(10518688,null,null,null,null,0,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        ERODED_BADLANDS = new Biome(19,"eroded_badlands",0.0,false,2.0,new Effects(12638463,10387789,9470285,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        FLOWER_FOREST = new Biome(20,"flower_forest",0.8,true,0.7,new Effects(12638463,null,null,null,null,7972607,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        FOREST = new Biome(21,"forest",0.8,true,0.7,new Effects(12638463,null,null,null,null,7972607,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        FROZEN_OCEAN = new Biome(22,"frozen_ocean",0.5,true,0.0,new Effects(12638463,null,null,null,null,8364543,3750089,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        FROZEN_PEAKS = new Biome(23,"frozen_peaks",0.9,true,-0.7,new Effects(12638463,null,null,null,null,8756735,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        FROZEN_RIVER = new Biome(24,"frozen_river",0.5,true,0.0,new Effects(12638463,null,null,null,null,8364543,3750089,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        GROVE = new Biome(25,"grove",0.8,true,-0.2,new Effects(12638463,null,null,null,null,8495359,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        ICE_SPIKES = new Biome(26,"ice_spikes",0.5,true,0.0,new Effects(12638463,null,null,null,null,8364543,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        JAGGED_PEAKS = new Biome(27,"jagged_peaks",0.9,true,-0.7,new Effects(12638463,null,null,null,null,8756735,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        JUNGLE = new Biome(28,"jungle",0.9,true,0.95,new Effects(12638463,null,null,null,null,7842047,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        LUKEWARM_OCEAN = new Biome(29,"lukewarm_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4566514,267827,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        LUSH_CAVES = new Biome(30,"lush_caves",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        MANGROVE_SWAMP = new Biome(31,"mangrove_swamp",0.9,true,0.8,new Effects(12638463,9285927,null,"swamp",null,7907327,3832426,5077600,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        MEADOW = new Biome(32,"meadow",0.8,true,0.5,new Effects(12638463,null,null,null,null,8103167,937679,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        MUSHROOM_FIELDS = new Biome(33,"mushroom_fields",1.0,true,0.9,new Effects(12638463,null,null,null,null,7842047,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        NETHER_WASTES = new Biome(34,"nether_wastes",0.0,false,2.0,new Effects(3344392,null,null,null,"minecraft:ambient.nether_wastes.loop",7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.nether_wastes.mood",6000,2,8),null,new Effects.AdditionSound("minecraft:ambient.nether_wastes.additions",0.0111),null)),
        OCEAN = new Biome(35,"ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        OLD_GROWTH_BIRCH_FOREST = new Biome(36,"old_growth_birch_forest",0.6,true,0.6,new Effects(12638463,null,null,null,null,8037887,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        OLD_GROWTH_PINE_TAIGA = new Biome(37,"old_growth_pine_taiga",0.8,true,0.3,new Effects(12638463,null,null,null,null,8168447,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        OLD_GROWTH_SPRUCE_TAIGA = new Biome(38,"old_growth_spruce_taiga",0.8,true,0.25,new Effects(12638463,null,null,null,null,8233983,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        PALE_GARDEN = new Biome(39,"pale_garden",0.8,true,0.7,new Effects(8484720,8883574,7832178,null,null,12171705,7768221,5597568,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        PLAINS = new Biome(40,"plains",0.4,true,0.8,new Effects(12638463,null,null,null,null,7907327,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        RIVER = new Biome(41,"river",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        SAVANNA = new Biome(42,"savanna",0.0,false,2.0,new Effects(12638463,null,null,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        SAVANNA_PLATEAU = new Biome(43,"savanna_plateau",0.0,false,2.0,new Effects(12638463,null,null,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        SMALL_END_ISLANDS = new Biome(44,"small_end_islands",0.5,false,0.5,new Effects(10518688,null,null,null,null,0,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        SNOWY_BEACH = new Biome(45,"snowy_beach",0.3,true,0.05,new Effects(12638463,null,null,null,null,8364543,4020182,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        SNOWY_PLAINS = new Biome(46,"snowy_plains",0.5,true,0.0,new Effects(12638463,null,null,null,null,8364543,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        SNOWY_SLOPES = new Biome(47,"snowy_slopes",0.9,true,-0.3,new Effects(12638463,null,null,null,null,8560639,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        SNOWY_TAIGA = new Biome(48,"snowy_taiga",0.4,true,-0.5,new Effects(12638463,null,null,null,null,8625919,4020182,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        SOUL_SAND_VALLEY = new Biome(49,"soul_sand_valley",0.0,false,2.0,new Effects(1787717,null,null,null,"minecraft:ambient.soul_sand_valley.loop",7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.soul_sand_valley.mood",6000,2,8),null,new Effects.AdditionSound("minecraft:ambient.soul_sand_valley.additions",0.0111),new Effects.Particle("minecraft:ash",0.00625))),
        SPARSE_JUNGLE = new Biome(50,"sparse_jungle",0.8,true,0.95,new Effects(12638463,null,null,null,null,7842047,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        STONY_PEAKS = new Biome(51,"stony_peaks",0.3,true,1.0,new Effects(12638463,null,null,null,null,7776511,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        STONY_SHORE = new Biome(52,"stony_shore",0.3,true,0.2,new Effects(12638463,null,null,null,null,8233727,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        SUNFLOWER_PLAINS = new Biome(53,"sunflower_plains",0.4,true,0.8,new Effects(12638463,null,null,null,null,7907327,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        SWAMP = new Biome(54,"swamp",0.9,true,0.8,new Effects(12638463,6975545,null,"swamp",null,7907327,6388580,2302743,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        TAIGA = new Biome(55,"taiga",0.8,true,0.25,new Effects(12638463,null,null,null,null,8233983,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        THE_END = new Biome(56,"the_end",0.5,false,0.5,new Effects(10518688,null,null,null,null,0,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        THE_VOID = new Biome(57,"the_void",0.5,false,0.5,new Effects(12638463,null,null,null,null,8103167,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        WARM_OCEAN = new Biome(58,"warm_ocean",0.5,true,0.5,new Effects(12638463,null,null,null,null,8103167,4445678,270131,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        WARPED_FOREST = new Biome(59,"warped_forest",0.0,false,2.0,new Effects(1705242,null,null,null,"minecraft:ambient.warped_forest.loop",7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.warped_forest.mood",6000,2,8),null,new Effects.AdditionSound("minecraft:ambient.warped_forest.additions",0.0111),new Effects.Particle("minecraft:warped_spore",0.01428))),
        WINDSWEPT_FOREST = new Biome(60,"windswept_forest",0.3,true,0.2,new Effects(12638463,null,null,null,null,8233727,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        WINDSWEPT_GRAVELLY_HILLS = new Biome(61,"windswept_gravelly_hills",0.3,true,0.2,new Effects(12638463,null,null,null,null,8233727,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        WINDSWEPT_HILLS = new Biome(62,"windswept_hills",0.3,true,0.2,new Effects(12638463,null,null,null,null,8233727,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        WINDSWEPT_SAVANNA = new Biome(63,"windswept_savanna",0.0,false,2.0,new Effects(12638463,null,null,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null)),
        WOODED_BADLANDS = new Biome(64,"wooded_badlands",0.0,false,2.0,new Effects(12638463,10387789,9470285,null,null,7254527,4159204,329011,new Effects.MoodSound("minecraft:ambient.cave",6000,2,8),null,null,null));
}