/*
* Autogenerated file. Please don't touch :)
* Class generator: dev.hypix.dataparser.registry.food.FoodParser (module data-parser)
* Date: Year: 2025. Month: 01. Day: 14. Time: 16:14:11
*/
package dev.hypix.reactor.api.item;
import lombok.Getter;

import java.util.Collection;

import dev.hypix.reactor.api.util.collection.CopyOnWriteCollection;

@Getter
public final class Food {

    public static final Collection<Food> ALL = new CopyOnWriteCollection<>(40);
    private final String name;
    private final char itemId;
    private final double foodPoints;

    public Food(String name, int itemId, double foodPoints) {
        this.name = name;
        this.itemId = (char)itemId;
        this.foodPoints = foodPoints;
    }

    private Food(String name, int itemId, double foodPoints, int index) {
        this(name, itemId, foodPoints);
        ALL.add(this);
    }

    public static final Food 
        APPLE = new Food("apple",831,4.0,0),
        MUSHROOM_STEW = new Food("mushroom_stew",880,6.0,1),
        BREAD = new Food("bread",886,5.0,2),
        PORKCHOP = new Food("porkchop",912,3.0,3),
        COOKED_PORKCHOP = new Food("cooked_porkchop",913,8.0,4),
        GOLDEN_APPLE = new Food("golden_apple",915,4.0,5),
        ENCHANTED_GOLDEN_APPLE = new Food("enchanted_golden_apple",916,4.0,6),
        COD = new Food("cod",984,2.0,7),
        SALMON = new Food("salmon",985,2.0,8),
        TROPICAL_FISH = new Food("tropical_fish",986,1.0,9),
        PUFFERFISH = new Food("pufferfish",987,1.0,10),
        COOKED_COD = new Food("cooked_cod",988,5.0,11),
        COOKED_SALMON = new Food("cooked_salmon",989,6.0,12),
        COOKIE = new Food("cookie",1029,2.0,13),
        MELON_SLICE = new Food("melon_slice",1033,2.0,14),
        DRIED_KELP = new Food("dried_kelp",1034,1.0,15),
        BEEF = new Food("beef",1037,3.0,16),
        COOKED_BEEF = new Food("cooked_beef",1038,8.0,17),
        CHICKEN = new Food("chicken",1039,2.0,18),
        COOKED_CHICKEN = new Food("cooked_chicken",1040,6.0,19),
        ROTTEN_FLESH = new Food("rotten_flesh",1041,4.0,20),
        SPIDER_EYE = new Food("spider_eye",1049,2.0,21),
        CARROT = new Food("carrot",1148,3.0,22),
        POTATO = new Food("potato",1149,1.0,23),
        BAKED_POTATO = new Food("baked_potato",1150,5.0,24),
        POISONOUS_POTATO = new Food("poisonous_potato",1151,2.0,25),
        GOLDEN_CARROT = new Food("golden_carrot",1153,6.0,26),
        PUMPKIN_PIE = new Food("pumpkin_pie",1162,8.0,27),
        RABBIT = new Food("rabbit",1170,3.0,28),
        COOKED_RABBIT = new Food("cooked_rabbit",1171,5.0,29),
        RABBIT_STEW = new Food("rabbit_stew",1172,10.0,30),
        MUTTON = new Food("mutton",1183,2.0,31),
        COOKED_MUTTON = new Food("cooked_mutton",1184,6.0,32),
        CHORUS_FRUIT = new Food("chorus_fruit",1202,4.0,33),
        BEETROOT = new Food("beetroot",1206,1.0,34),
        BEETROOT_SOUP = new Food("beetroot_soup",1208,6.0,35),
        SUSPICIOUS_STEW = new Food("suspicious_stew",1244,6.0,36),
        SWEET_BERRIES = new Food("sweet_berries",1269,2.0,37),
        GLOW_BERRIES = new Food("glow_berries",1270,2.0,38),
        HONEY_BOTTLE = new Food("honey_bottle",1277,6.0,39);
}